/* Relocation types, string version for debugging */

static const char * const _dl_reltypes_tab[] =
{
	[0]	"R_MIPS_NONE",		"R_MIPS_16",		"R_MIPS_32",
	[3]	"R_MIPS_REL32",		"R_MIPS_26",		"R_MIPS_HI16",
	[6]	"R_MIPS_LO16",		"R_MIPS_GPREL16",	"R_MIPS_LITERAL",
	[9]	"R_MIPS_GOT16",		"R_MIPS_PC16",		"R_MIPS_CALL16",
	[12]	"R_MIPS_GPREL32",
	[16]	"R_MIPS_SHIFT5",	"R_MIPS_SHIFT6",	"R_MIPS_64",
	[19]	"R_MIPS_GOT_DISP",	"R_MIPS_GOT_PAGE",	"R_MIPS_GOT_OFST",
	[22]	"R_MIPS_GOT_HI16",	"R_MIPS_GOT_LO16",	"R_MIPS_SUB",
	[25]	"R_MIPS_INSERT_A",	"R_MIPS_INSERT_B",	"R_MIPS_DELETE",
	[28]	"R_MIPS_HIGHER",	"R_MIPS_HIGHEST",	"R_MIPS_CALL_HI16",
	[31]	"R_MIPS_CALL_LO16",	"R_MIPS_SCN_DISP",	"R_MIPS_REL16",
	[34]	"R_MIPS_ADD_IMMEDIATE",	"R_MIPS_PJUMP",		"R_MIPS_RELGOT",
	[37]	"R_MIPS_JALR",
};
